### ISSUE TITLE
Update default map tiles to Stamen

### ISSUE THREAD

**Issue by MrkGrgsn** [pduchesne/ckanext-geoview#7]
CKAN and ckanext-spatial are now using Stamen map tiles as the default map tiles, following MapQuest changing their access terms and requiring an account. It would be great if geoview used the same default.

See https://github.com/ckan/ckanext-spatial/commit/44f05e181c4c70e3b062fec49e0f2251b52610a1

**Comment by pduchesne** [comment]
Done now. (merged from ckan/ckanext-geoview)
